# Generated by Django 5.1.7 on 2025-03-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_comment_category_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
